tap "homebrew/bundle"
tap "homebrew/services"
brew "zoxide"
brew "colima"
brew "bat"
brew "mas"
brew "docker"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fswatch"
brew "fzf"
brew "git"
brew "jq"
brew "speedtest-cli"
brew "gemini-cli"
brew "zsh"
cask "obsidian"
brew "npm"
cask "jordanbaird-ice"
cask "meetingbar"
# cask "deepl"
cask "tigervnc-viewer"
cask "cursor"
cask "warp"
cask "zen-browser"
cask "music-decoy"

cask "arc"
cask "winbox"
# cask "adguard"
cask "aldente"
cask "amneziavpn"
cask "anytype"
cask "capcut"
cask "chatgpt"
cask "clop"
cask "datagrip"
cask "dbeaver-community"
cask "figma"
cask "goland"
cask "iina"
cask "insta360-studio"
cask "intellij-idea"
cask "miro"
cask "pycharm"
# raycast: используем Raycast X (Beta) — cask'а нет, ставится вручную (см. README → Manual).
# Классический cask "raycast" не возвращать: обе версии клеймят схему raycast://,
# и диплинки расширений уходят не в ту копию.
cask "telegram"
cask "transmission"
cask "zoom"
cask "yandex-music"
cask "alt-tab"
cask "betterdisplay"
cask "karabiner-elements"

vscode "akamud.vscode-theme-onedark"
vscode "janisdd.vscode-edit-csv"
vscode "mechatroner.rainbow-csv"
vscode "tfgzs.diff-clipboard"

mas 'Caramba Switcher', id: 1565826179 
mas 'Dropover', id: 1355679052
mas 'Wireguard', id: 1451685025
mas 'Spark', id: 6445813049