#!/bin/bash
set -eu

cd "$(dirname $0)"

bold=$(tput bold)
green=$(tput setaf 2)
normal=$(tput sgr0)

title() {
  echo "${bold}==> $1${normal}"
  echo
}

indent() {
  sed 's/^/  /'
}

echo

install_simlinks_to_home() {
  title "Configuring symlinks..."
  sh ./scripts/install-symlinks
}

##########################################################

while [[ $# -gt 0 ]]; do
  case "$1" in
    -u|--update-symlinks)
      install_simlinks_to_home
      echo "${green}Symlinks updated!${normal}" | indent
      exit 0
      ;;
    -h|--help)
      echo "Usage: $0 [options]"
      echo "  -u, --update-symlinks"
      echo "  -h, --help           "
      exit 0
      ;;
    *)
      echo "Unknown flags: $1"
      echo "Use -h to see option."
      ;;
  esac
  shift
done

# Install Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  title "Installing Oh My Zsh..."
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  echo
fi

# Install brew
if test ! $(which brew); then
  title "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Install brew packages
title "Installing software..."
brew bundle | indent
echo

eval "$(/opt/homebrew/bin/brew shellenv)"
# Ensure zsh is a valid shell option
if ! cat /etc/shells | grep $HOMEBREW_PREFIX/bin/zsh > /dev/null; then
  title "Adding zsh to list of allowed shells..."
  sudo sh -c "echo $HOMEBREW_PREFIX/bin/zsh >> /etc/shells"
  echo
fi

# If macOS
if [[ "$(uname)" == "Darwin" ]]; then

  # Use Touch ID for sudo
  if [ ! -f /etc/pam.d/sudo_local ]; then
    echo "auth       sufficient     pam_tid.so" | sudo tee /etc/pam.d/sudo_local
  fi

  title "Configuring macOS..."
  sh ./scripts/configure-macos-settings
  echo "Defaults configured!" | indent
  echo

fi

install_simlinks_to_home

# Check that we are using zsh
if [[ "$SHELL" != *"zsh"* ]]; then
  if [[ "$(uname)" == "Darwin" ]]; then
    title "Changing user shell to zsh..."
    chsh -s $HOMEBREW_PREFIX/bin/zsh
    echo "Your shell has been changed to zsh, please restart your terminal or tab" | indent
    echo
  else
    echo "You are not using zsh, after installing, please run 'chsh -s /path/to/zsh'" | indent
    echo
  fi
fi
  
title "Turning off spotlight..."
sudo mdutil -i off

echo "${green}All done!${normal}" | indent
